fastlane_version "2.40.0"

default_platform :ios

platform :ios do
  before_all do
    carthage(platform: "iOS")
  end

  desc "Build artifact"
  lane :build_artifact do
    gym(scheme: "Smashtag", workspace: "Smashtag.xcworkspace")
  end

  desc "Codesign"
  lane :sign do
    cert
    sigh
    gym(scheme: "Smashtag", workspace: "Smashtag.xcworkspace")
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "Smashtag", workspace: "Smashtag.xcworkspace", device: "iPhone 7", test_without_building: false)
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    gym
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    gym
    deliver(force: true)
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
